### ISSUE TITLE
 data missing

### ISSUE THREAD

**Issue by thuliu-yt16** [yizhiwang96/deepvecfont#1]
Could you provide the extra training data for image superresolution and neural rasterizer? The missing data seem to includes`./data/mean.npz`, `./data/stdev.npz` and `./data/glyphss_dataset`. Thanks!

**Comment by yizhiwang96** [comment]
> Could you provide the extra training data for image superresolution and neural rasterizer? The missing data seem to includes`./data/mean.npz`, `./data/stdev.npz` and `./data/glyphss_dataset`. Thanks!

Hi, Yingtian. I will upload these files ASAP.
