### ISSUE TITLE
Can the generated svg sequences from the network be used to generate a font directly for use? 

### ISSUE THREAD

**Issue by Kiode** [yizhiwang96/deepvecfont#15]
Can the generated svg sequences from the network be used to generate a font file (e.g., .ttf file) directly for use? Will the font size and other factors affect the visual effect in actual use?

**Comment by yizhiwang96** [comment]
Hi Kiode,
I think there are some tools that can convert SVGs into TTF files.
An issue could be `Ethics of AI`. I'm not sure if the results can be used as commercial uses.
Another issue is that our results are not so perfect as human-designed (for example, small round corners tend to lose smothness after doing refinement).

**Comment by Kiode** [comment]
Thank you for your kind reply. I'm not looking for commercial use, just curious if the generated SVG files will throw errors when converted to TTF files.
