### ISSUE TITLE
No such glyph 

### ISSUE THREAD

**Issue by Johnson-yue** [yizhiwang96/deepvecfont#20]
I used ‘data/utils/convert_ttf_to_sfd_mp.py’  and add '0123456789' after charset, so the finally charset is "a-zA-Z**0-9**".

when convert "a-zA-Z" it is success, but it failed when char is "0"  
`TypeError:No such glyph`  
the error code is `line 61   char_description.write(str(new_font_for_char[char].width) + "\n")` 

I check the font  and it has "0" glyph in ttf file

**Comment by Johnson-yue** [comment]
I close this  because, in fontforge, 0  = "zero"  so
`new_font_for_char["zero"].width ` it works

**Comment by yizhiwang96** [comment]
> 

Thank you for sharing this solution.
We also found reading non-latin characters needs unicodes to be the indexes.
