### ISSUE TITLE
font list used for training/testing 

### ISSUE THREAD

**Issue by thuliu-yt16** [yizhiwang96/deepvecfont#23]
It seems that the `font_ttfs.zip` includes many fonts and only a subset of it is used for training and testing. So could you please provide the font list you used?

**Comment by yizhiwang96** [comment]
It seems the log file output by our preprocess script will record which fonts are filtered out. Please check it out. Thanks!

**Comment by yizhiwang96** [comment]
You can also check the font id entry ([pkl](https://github.com/yizhiwang96/deepvecfont/blob/e3bd2e48aa887d6638d06b405654fca6a1832164/data_utils/write_data_to_pkl.py#L59) or [dirs](https://github.com/yizhiwang96/deepvecfont/blob/e3bd2e48aa887d6638d06b405654fca6a1832164/data_utils/write_data_to_dirs.py#L108)) in our dataset.

**Comment by thuliu-yt16** [comment]
Thanks! The font id entry in pkl makes sense. But some fonts in `font_ttfs.zip` are corrupted. Anyway, I could get the ground truth font SVGs by running `test_sf.py`.
