### ISSUE TITLE
How to test the model with my own glyphs?

### ISSUE THREAD

**Issue by christinalc** [yizhiwang96/deepvecfont#27]
Hi, thank you for making this! I am trying to test the model by inputting my own SVG glyphs and with the goal of returning the results in the experiments folder. However, I can't figure out how to input my own data. From my understanding, the current test data is coming from `data/vecfont_dataset_dirs/test/test_all.pkl`. Do I need to format my data as a .pkl file? How can I achieve this?

**Comment by yizhiwang96** [comment]
Hi,

Currently we support building dataset from TTFs/OTFs, please see this [instruction](https://github.com/yizhiwang96/deepvecfont#customize-your-own-dataset) for details.

(1) For quick use, you can first convert SVGs into TTFs/OTFs and then run our code. Tools are like [SVG2TTF](https://www.npmjs.com/package/svg2ttf), [SVG2OTF](https://everythingfonts.com/svg-to-otf).

(2) Another way is to convert SVG into our data format (Fig. 4 in our [paper](https://arxiv.org/pdf/2110.06688.pdf)), which could take some time to write the code.

We released the code of few-shot generation. For interpolations and random generation, it is easy to implement by refering to the few-shot generation code.

**Comment by christinalc** [comment]
Thank you for the reply, I will try it!
