### ISSUE TITLE
Questions about the glyph images

### ISSUE THREAD

**Issue by hyh-dev** [yizhiwang96/deepvecfont#5]
Hi, I found that some glyph images in ground truth are missing some of the handwriting. Where did i go wrong ？
![image](https://user-images.githubusercontent.com/47145422/138550574-2d7d2542-bbf4-47e1-8640-7db9478a846c.png)

**Comment by graphl** [comment]
@yizhiwang96 
Why do you need to fix baselines?
What happens if I keep the data below the baseline?
If I want to get the generated font baseline information, do I need to convert the generated SVG and BMP to fonts?
