### ISSUE TITLE
About the main model

### ISSUE THREAD

**Issue by SwordBearFire** [yizhiwang96/deepvecfont#6]
Hi, 

Thank you for releasing the amazing repo. Could you tell me when you'll upload the main model? 

Thank you again.

Sincerely yours.

**Comment by yizhiwang96** [comment]
> Hi,
> 
> Thank you for releasing the amazing repo. Could you tell me when you'll upload the main model?
> 
> Thank you again.
> 
> Sincerely yours.

Hi Sword. I will spend some time to evaluate the checkpoints and release the best one. 
Before that you could try to train the model by yourself. Thank you!

**Comment by yizhiwang96** [comment]
> Hi,
> 
> Thank you for releasing the amazing repo. Could you tell me when you'll upload the main model?
> 
> Thank you again.
> 
> Sincerely yours.

Hi, Sword. I have uploaded the pretrained [main model](https://drive.google.com/drive/folders/1Ykacqk8VPhvVv_XFH47BBvGt8ZlBrpnZ?usp=sharing). I didn't evaluate each one, but the released one looks good.

**Comment by SwordBearFire** [comment]
> > Hi,
> > Thank you for releasing the amazing repo. Could you tell me when you'll upload the main model?
> > Thank you again.
> > Sincerely yours.
> 
> Hi, Sword. I have uploaded the pretrained [main model](https://drive.google.com/drive/folders/1Ykacqk8VPhvVv_XFH47BBvGt8ZlBrpnZ?usp=sharing). I didn't evaluate each one, but the released one looks good.

Thank you very much!
