### ISSUE TITLE
How can I not draw pictures through write_glyph_imgs.py

### ISSUE THREAD

**Issue by lixinjie97** [yizhiwang96/deepvecfont#7]

**Comment by yizhiwang96** [comment]
Hi, what does "not draw poctures" mean? You can send me emails to describe your problems.

**Comment by lixinjie97** [comment]
I made my own data set，ground truth have no content.
![Uploading 3b03ca9497d9dc66(1).jpg…]()

**Comment by lixinjie97** [comment]
I made my own data set，ground truth have no content.
![Uploading xx.jpg…]()

**Comment by lixinjie97** [comment]
I made my own data set，ground truth have no content.
![xx](https://user-images.githubusercontent.com/47939915/144775728-3195ee66-e5e8-49ec-a3b5-036eb4a1e4af.jpg)

**Comment by yizhiwang96** [comment]
In Line 72 of write_glyph_imgs.py, add codes:
```
image.save('tmp.png')
input()
```
Check `tmp.png` to find whether the problem occurs here.

**Comment by yizhiwang96** [comment]
> I made my own data set，ground truth have no content. ![xx](https://user-images.githubusercontent.com/47939915/144775728-3195ee66-e5e8-49ec-a3b5-036eb4a1e4af.jpg)

I have found where the problem is. I have fixed the code. See for [this](https://github.com/yizhiwang96/deepvecfont/commit/31a98477a85a4826f678091d966d44ceb071fad2) for details.
