### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by Yancy-lv** [yizhiwang96/deepvecfont#9]
![O}U6Q$Z7@)JM 9XXTCH32AB](https://user-images.githubusercontent.com/95954197/145698192-02569173-1de7-4690-bf6a-0ab1c12d405e.png)

**Comment by yizhiwang96** [comment]
The format of your path is wrong, i.e., 'data/vecfont_dataset\\train\\train_all.pkl'.

**Comment by yizhiwang96** [comment]
> ![O}U6Q$Z7@)JM 9XXTCH32AB](https://user-images.githubusercontent.com/95954197/145698192-02569173-1de7-4690-bf6a-0ab1c12d405e.png)

My experiments were running on Linux, so you need to do some modifications by changing '/' to '\\' in the path names.
